name: Demo workflow
on: push
jobs:
    print:
       runs-on: ${{ martix.os }}
       steps:
            - name: Print greeeting ${{ martix.os }}
              run: echo "Hello, my friend!"
            - name: Print several lines
              run: |
                echo "1st line"
                echo "2nd line"
                echo "3rd line"
