name: Demo workflow
on: workflow_dispatch
jobs:
    print:
       runs on: windows
       steps:
           - name: Print greeting
               run: echo "Hello, my friend!"
               
       
