name: Demo workflow
on: push
jobs:
    print:
       runs-on: ${{matrix.oss}}
       strategy:
         matrix:
           oss: [ubuntu-latest, windows-latest]
       steps:
         - name: Print greeeting ${{ matrix.oss }}
           run: echo "Hello, my friend!"
         - name: Print several lines
           run: |
             echo "1st line"
             echo "2nd line"
             echo "3rd line"
