name: Demo workflow
on: workflow_dispatch
jobs:
    print:
       runs-on: ubuntu-latest
       steps:
            - name: Print greeeting
              run: echo "Hello, my friend!"
            - name: Print several lines
              run: |
                echo "1st line"
                echo "2nd line"
                echo "3rd line"
